project:
  type: manuscript
manuscript:
  article: harpur-dunlop-wulatji.qmd
  code-links:
    - text: Harpur Data
      icon: file-spreadsheet
      href: data/harpur-lang.xlsx
    - text: Dunlop Data
      icon: file-spreadsheet
      href: data/dunlop-lang.xlsx
    - text: Topographic Data
      icon: globe
      href: https://pid.geoscience.gov.au/dataset/ga/60804
    - text: Town geocoding script
      icon: globe
      href: scripts/geocode-towns.R
format:
  html:
    smooth-scroll: true
  # sagej-pdf:
  #   classoption: [Crown,times,sageh]
  #   # Allow more than 10 footnotes
  #   header-includes: |
  #     \usepackage[perpage]{footmisc}
  docx: default
execute:
  freeze: auto
